### ISSUE TITLE
Display connection error if front end cannot connect to API server

### ISSUE THREAD

**Issue by ciminelli** [tableflowhq/tableflow#11]
Whenever a component in React is loaded, call the `api/health` endpoint with a short (10 seconds) timeout to check if the front end is able to connect to the API server.

If the connection is not successful, return an error page component with any details about the connection error.

We currently don't have an error page component but can make one quickly.

**Comment by AkshayAwate** [comment]
@ciminelli would you provide more info about this issue, would love pick up this issue. Thanks

**Comment by ciminelli** [comment]
> @ciminelli @mpatin would you provide more info about this issue, would love pick up this issue. Thanks

That sounds great, I just added more to the description. I think we could add a universal `useEffect` call on each component to do this. Let me know how else I can help!

**Comment by AkshayAwate** [comment]
> > @ciminelli @mpatin would you provide more info about this issue, would love pick up this issue. Thanks
> 
> That sounds great, I just added more to the description. I think we could add a universal `useEffect` call on each component to do this. Let me know how else I can help!

Thanks, I was looking for backend, this seems to frontend  task.

**Comment by zenoR-git** [comment]
hello is this issue still open. would love to pick up this issue

**Comment by kingsoo123** [comment]
@ciminelli kindly let me know if this issue is still open? Thanks

**Comment by ciminelli** [comment]
@kingsoo123 it is not, I'll close it out. We'll be working on some issues in the near future to onboard to contributing and I can keep you updated on Slack. Thanks for your support!
