### ISSUE TITLE
xls support?

### ISSUE THREAD

**Issue by gammons** [tableflowhq/tableflow#113]
Hi all,

This looks like a fantastic tool.  I'm wondering if you have a public roadmap somewhere - a lot of my clients have XLSX files that they import and it would be great it Tableflow supported that.  Thanks!

**Comment by ciminelli** [comment]
Hey @gammons! We currently support XLSX but there are a few improvements we want to make such as sheet selection, being better at parsing data when it's in a non-standard format, ignoring graphs, etc.

Were there any features you had top of mind for XLSX support?

We're also currently looking at the best place to host our public roadmap as it's important for everyone to see what's in progress, be able to request features, and vote on what we work on next—stay tuned for this!

**Comment by gammons** [comment]
Oh awesome, I wasn't aware that tableflow supported XLS imports!  Might be worth calling out in your README :smile:

**Comment by ciminelli** [comment]
@gammons good callout 😄 will get that updated. Keep us posted with any feature requests or feedback as you play around with the platform!
