### ISSUE TITLE
May I ask, what is the reason for this?

### ISSUE THREAD

**Issue by yx3016** [tableflowhq/tableflow#192]
Unable to connect. Check your connection and reach out to support if the problem persists.
![image](https://github.com/tableflowhq/tableflow/assets/81002806/ec769485-5074-43ed-9427-731b669ee0dd)

>
 `
git clone https://github.com/tableflowhq/tableflow.git
cd tableflow
cp .env.example .env
docker-compose up -d
`
 
![image](https://github.com/tableflowhq/tableflow/assets/81002806/b2ef37c7-daab-41e6-8f77-0f73f1abc624)

**Comment by ciminelli** [comment]
Hi @yx3016, can you open your chrome network console, refresh the page, and send any errors that show up there?

**Comment by yx3016** [comment]
> Hi @yx3016, can you open your chrome network console, refresh the page, and send any errors that show up there?

![image](https://github.com/tableflowhq/tableflow/assets/81002806/67722ab4-ff52-496e-8175-1319ed160010)

**Comment by ciminelli** [comment]
@yx3016 you can update your `.env` file to include this line:

`TABLEFLOW_WEB_IMPORTER_URL=http://172.32.101.222:3001`

And then restart the docker container using `docker-compose up -d`

**Comment by yx3016** [comment]
> @yx3016 you can update your `.env` file to include this line (needed for CORS):
> 
> `TABLEFLOW_WEB_IMPORTER_URL=http://172.32.101.222:3001`
> 
> And then restart the docker container using `docker-compose up -d`

Okay, I'll give it a try

**Comment by yx3016** [comment]
@ciminelli 
Still the same

![image](https://github.com/tableflowhq/tableflow/assets/81002806/a9f685c5-2457-4b1e-b06b-ed8ac37e32a5)

![image](https://github.com/tableflowhq/tableflow/assets/81002806/e11b5eee-75d3-4636-96ab-5bcc320812f9)

**Comment by yx3016** [comment]
I have found the reason, it is that our routing settings conflict with the program. After resolving the routing issue, the status is as follows.
![image](https://github.com/tableflowhq/tableflow/assets/81002806/67542052-c095-4729-8f1b-3f2eb1cdbd14)

**Comment by yx3016** [comment]
Suggestion! Do you provide a packaged Docker standard container! 
Haha

**Comment by ciminelli** [comment]
The docker images are in the docker-compose file. They should be in use on your setup already!

And it looks like it's working now. You'll need to now set the SDK up in your app, and use the `template` parameter to add your template: https://tableflow.com/docs/templates

Here's an example with the [React SDK](https://tableflow.com/docs/sdk/react) you can use:

```
<TableFlowImporter
  hostUrl={"http://172.32.101.222:3001"}
  darkMode={true}
  primaryColor="#7A5EF8"
  metadata={'{"userId": 1234, "userEmail": "test@example.com"}'}
  onComplete={(data) => {
    console.log(data);
  }}
  template={{
    columns: [
      {
        name: "First Name",
        key: "first_name",
        required: true,
        description: "The first name of the user",
        suggested_mappings: ["First", "Name"],
        data_type: "string",
        validations: [
          {
            validate: "not_blank",
            message: "Cell must contain a value",
          },
        ],
      },
      {
        name: "User ID",
        data_type: "string",
        validations: [
          {
            validate: "regex",
            options: "^[a-zA-Z0-9]*$",
            message: "Cell can only contain letter or numbers",
          },
        ],
      },
      {
        name: "Joined On",
        data_type: "date",
      },
      {
        name: "Active",
        data_type: "boolean",
      },
    ],
  }}
/>
```

**Comment by umer936** [comment]
I have the same error trying to put tableflow behind https. 

I changed the `/etc/nginx/conf.d/default.conf` to include the ssl certs and listen on 443 and so now the site (which is on https) can connect to the importer-ui just fine. But now the file-import does not listen on https so I get a CORS issue.
