### ISSUE TITLE
Add support for SSH tunnels

### ISSUE THREAD

**Issue by ciminelli** [tableflowhq/tableflow#24]
This should be an option to connect to the database instead of connecting to the Postgres host directly.

We'll need to:

1. Add a new option to the "Connect Database" page
3. Update the connect-database endpoint to support the SSH options (server host, connection port, login username, key or password authentication)
4. Support SSH key authentication or password authentication

More info can be found with how Airbyte supports this type of connection: https://docs.airbyte.com/integrations/sources/postgres/#connect-via-ssh-tunnel

**Comment by AkshayAwate** [comment]
> _No description provided._

@ciminelli looking for more description.

**Comment by ciminelli** [comment]
> > _No description provided._
> 
> @ciminelli looking for more description.

Just updated the description, let me know if this is something you'd be interested in and I can work with you on it!

**Comment by AkshayAwate** [comment]
Yeah, This is my understanding
current workflow, install inquery and then add details of postgres host, then connect. So now instead of connecting directly to postgres host, now we can have "Connect Database" page, so this will connect using ssh as per this [doc](https://docs.airbyte.com/integrations/sources/postgres/#connect-via-ssh-tunnel). Am i right ? please feel free to correct 😄.

**Comment by ciminelli** [comment]
> Yeah, This is my understanding: Current workflow, install inquery and then add details of postgres host, then connect. So now instead of connecting directly to postgres host, now will have "Connect Database" page, so this will connect using ssh as per this [doc](https://docs.airbyte.com/integrations/sources/postgres/#connect-via-ssh-tunnel). Am i right ? please feel free to correct 😄.

Yes, but the SSH connection option will be right on the connect database page! We can make a dropdown to select the SSH connection option.
