### ISSUE TITLE
Get started on the Docs page is not responsive    bug!!!!

### ISSUE THREAD

**Issue by flexzy2011** [tableflowhq/tableflow#28]
on the home page when you scroll up to the navbar and click on Docs. routing to the Docs page and clicking on Get started makes the screen blank. but checking the browser path you see( https://app.tableflow.com/singup), it's not working.

**Comment by mpatin** [comment]
thanks for the report @flexzy2011! Just pushed a fix: 

https://github.com/tableflowhq/tableflow/commit/c83de5d13b743671474a98ee31bdd91a11d21ac3

**Comment by mpatin** [comment]
thanks for the report @flexzy2011! Just pushed a fix: https://github.com/tableflowhq/tableflow/commit/c83de5d13b743671474a98ee31bdd91a11d21ac3

**Comment by flexzy2011** [comment]
You’re welcome.. that’s nice 👍🏾
