### ISSUE TITLE
Features in Docs need briefing details

### ISSUE THREAD

**Issue by OLAMILEKANSI5** [tableflowhq/tableflow#44]
### Add a brief descriptive details to those listed features in the Doc

**Comment by ciminelli** [comment]
Thanks @OLAMILEKANSI5—we're working on this now among other improvements for better onboarding.

**Comment by OLAMILEKANSI5** [comment]
@ciminelli Can i suggest some additional brief details to them on a pull request to ease 
workload

**Comment by ciminelli** [comment]
@OLAMILEKANSI5 sounds good to me!

**Comment by OLAMILEKANSI5** [comment]
Alright, Let me get to work now
