### ISSUE TITLE
Custom request headers

### ISSUE THREAD

**Issue by marcklingen** [tableflowhq/tableflow#7]
Many APIs that I would like to use as an action target require _header-based authentication_. For example, it would be great to directly push events generated by inquery to Segment ([HTTP Tracking API](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/)) to pipe the events to marketing tools and our data warehouse.

More generalized: Being able to set _custom request headers_ (key/value similar to Postman) would be a great add-on to inquery to reduce the need to proxy the request when trying to integrate with more targets.

**Comment by c-nv-s** [comment]
Might also be useful if the actual authentication key used in the header could somehow be referenced from an environment variable, or retrieved feom the db.
